disabled_rules:
  - closing_brace
  - opening_brace
  - identifier_name
  - type_name
  - trailing_whitespace
  - nesting
  - todo
  - force_cast
  - force_try

excluded:
  - Carthage

trailing_whitespace:
  severity: error

line_length:
  warning: 200
  error: 200

trailing_comma:
  mandatory_comma: true

# Custom config

function_body_length:
  warning: 1000
  error: 2000


type_body_length:
  warning: 1000
  error: 2000

file_length:
  warning: 2000
  error: 2500
